-- =====================================================================
-- Tabla de testimonios para DentiBox.
-- Ejecuta esto en Supabase SQL Editor una sola vez.
-- =====================================================================

create table if not exists testimonios (
  id bigint generated by default as identity primary key,
  auth_user_id uuid references auth.users(id) on delete cascade,
  nombre text not null,
  estrellas int not null check (estrellas between 1 and 5),
  comentario text not null,
  created_at timestamp with time zone default now()
);

-- Permite leer testimonios a cualquier visitante.
create policy "public_select_testimonios" on testimonios
  for select
  to public
  using (true);

-- Permite a un usuario autenticado crear su propio testimonio.
-- Si quieres reforzar que solo cuentas verificadas puedan enviar,
-- necesitas agregar metadata de verificación al JWT o validar en el
-- backend con una función adicional.
create policy "authenticated_insert_testimonios" on testimonios
  for insert
  to authenticated
  with check (auth.uid() = auth_user_id);
